spring:
  datasource:
    url: jdbc:p6spy:h2:~/testdb
    #driver-class-name: org.h2.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: sa
    password:
    schema: classpath:db/schema.sql
    #data: classpath:db/data.sql
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    org: debug
    edu: debug